var AiDraftService = (function () {
  function draft(visitId,requestId) {
    var actor = Auth.requireRoles(['ADMIN', 'EVALUATOR', 'DIRECTIVE']), visit = VisitService.get(visitId); if (!VisitState.isEditable(visit.status)) throw AppErrors.validation('La evaluación no se puede editar.');
    var input={observationRecord:visit.observationRecord||'',generalResponses:(visit.generalResponses||[]).map(function(r){return {result:r.result,argument:r.argument};}),rubricResponses:(visit.rubricResponses||[]).map(function(r){return {level:r.level,descriptor:r.descriptorSnapshot,observation:r.observation};})};
    var start=Date.now(),config=AppConfig.get(),record={ai_request_id:Utilities.getUuid(),visit_id:visitId,data_version:visit.dataVersion,provider:config.aiProvider,model:config.aiModel,prompt_version:config.aiPromptVersion,input_hash:JsonUtil.hash(input),requested_at:JsonUtil.now(),requested_by:actor.user_id,accepted:false,human_edited:false};
    try { var result=AiGateway.generate(input); record.status='SUCCESS'; record.latency_ms=Date.now()-start; record.output_json=JSON.stringify(result); SheetsRepository.append('AI_REQUESTS',record); Audit.write(actor,'AI_DRAFT_GENERATED','VISIT',visitId,visit.dataVersion,requestId,'SUCCESS','Borrador IA generado'); return {requestId:record.ai_request_id,draft:result}; }
    catch(e){record.status='ERROR';record.latency_ms=Date.now()-start;record.error_code=e.code||'AI_UNAVAILABLE';SheetsRepository.append('AI_REQUESTS',record);Audit.write(actor,'AI_DRAFT_FAILED','VISIT',visitId,visit.dataVersion,requestId,'ERROR','Falló borrador IA',{code:record.error_code});throw e;}
  }
  function accept(aiRequestId,humanEdited,requestId) { var actor = Auth.requireRoles(['ADMIN', 'EVALUATOR', 'DIRECTIVE']), row = SheetsRepository.find('AI_REQUESTS','ai_request_id',aiRequestId);if(!row)throw AppErrors.notFound('La solicitud de IA');var visit=VisitService.raw(row.visit_id);Auth.assertVisit(actor,visit,true);row.accepted=true;row.human_edited=!!humanEdited;row.accepted_at=JsonUtil.now();SheetsRepository.upsert('AI_REQUESTS',['ai_request_id'],row);Audit.write(actor,'AI_DRAFT_ACCEPTED','VISIT',row.visit_id,row.data_version,requestId,'SUCCESS','Borrador IA aceptado',{humanEdited:!!humanEdited});return true; }
  return {draft:draft,accept:accept};
})();
