function createStarterTemplates() {
  var actor=Auth.requireRoles(['ADMIN']),props=PropertiesService.getScriptProperties(),config=AppConfig.get();
  var root=config.templatesFolderId?DriveApp.getFolderById(config.templatesFolderId):DriveApp.createFolder('Visitas Aulicas - Plantillas '+config.environment);
  if(!config.templatesFolderId)props.setProperty('TEMPLATES_FOLDER_ID',root.getId());
  var output=config.outputFolderId?DriveApp.getFolderById(config.outputFolderId):DriveApp.createFolder('Visitas Aulicas - PDFs '+config.environment);if(!config.outputFolderId)props.setProperty('OUTPUT_FOLDER_ID',output.getId());
  var temp=config.tempFolderId?DriveApp.getFolderById(config.tempFolderId):DriveApp.createFolder('Visitas Aulicas - Temporales '+config.environment);if(!config.tempFolderId)props.setProperty('TEMP_FOLDER_ID',temp.getId());
  var keys={ANNEX_1:'ANNEX1_TEMPLATE_ID',ANNEX_2:'ANNEX2_TEMPLATE_ID',ANNEX_3:'ANNEX3_TEMPLATE_ID',ANNEX_5:'ANNEX5_TEMPLATE_ID',FULL_PACKAGE:'FULL_PACKAGE_TEMPLATE_ID'};
  Object.keys(keys).forEach(function(type){if(props.getProperty(keys[type]))return;var doc=DocumentApp.create('Plantilla '+type+' '+config.environment),body=doc.getBody();body.clear();appendTemplateSection_(body,type);doc.saveAndClose();var file=DriveApp.getFileById(doc.getId());file.moveTo(root);props.setProperty(keys[type],doc.getId());});
  Audit.write(actor,'STARTER_TEMPLATES_CREATED','CONFIG','','','setup','SUCCESS','Plantillas iniciales creadas');return {templatesFolderId:root.getId(),outputFolderId:output.getId(),tempFolderId:temp.getId()};
}
function appendTemplateSection_(body,type){
  body.appendParagraph('{{DOCUMENT_TITLE}}').setHeading(DocumentApp.ParagraphHeading.TITLE);
  body.appendParagraph('Código: {{VISIT_ID}}     Fecha: {{VISIT_DATE}}');body.appendParagraph('Institución: {{INSTITUTION_NAME}}');body.appendParagraph('Docente: {{TEACHER_NAME}}     Curso: {{COURSE}}');body.appendParagraph('Asignatura: {{SUBJECT}}     Tema: {{CONTENT_TOPIC}}');
  if(type==='ANNEX_1'){body.appendParagraph('Registro de la observación').setHeading(DocumentApp.ParagraphHeading.HEADING1);body.appendParagraph('{{OBSERVATION_RECORD}}');body.appendParagraph('Documentación física').setHeading(DocumentApp.ParagraphHeading.HEADING2);body.appendParagraph('{{EVIDENCE_CHECKS}}');}
  if(type==='ANNEX_2'){body.appendParagraph('Datos informativos').setHeading(DocumentApp.ParagraphHeading.HEADING1);body.appendParagraph('Ubicación: {{LOCATION}}  Jornada: {{SHIFT}}  Estudiantes: {{STUDENT_COUNT}}');body.appendParagraph('Criterios generales').setHeading(DocumentApp.ParagraphHeading.HEADING1);body.appendParagraph('{{GENERAL_CRITERIA_TABLE}}');body.appendParagraph('Resultados de la rúbrica').setHeading(DocumentApp.ParagraphHeading.HEADING1);body.appendParagraph('{{RUBRIC_SELECTIONS_TABLE}}');}
  if(type==='ANNEX_3'){body.appendParagraph('Rúbrica de observación').setHeading(DocumentApp.ParagraphHeading.HEADING1);body.appendParagraph('{{RUBRIC_SELECTIONS_TABLE}}');}
  if(type==='ANNEX_5'){appendFeedback_(body);}
  if(type==='FULL_PACKAGE'){body.appendParagraph('ANEXO 1').setHeading(DocumentApp.ParagraphHeading.HEADING1);body.appendParagraph('{{OBSERVATION_RECORD}}');body.appendPageBreak();body.appendParagraph('ANEXO 2').setHeading(DocumentApp.ParagraphHeading.HEADING1);body.appendParagraph('{{GENERAL_CRITERIA_TABLE}}');body.appendParagraph('{{RUBRIC_SELECTIONS_TABLE}}');body.appendPageBreak();body.appendParagraph('ANEXO 3').setHeading(DocumentApp.ParagraphHeading.HEADING1);body.appendParagraph('{{RUBRIC_SELECTIONS_TABLE}}');body.appendPageBreak();body.appendParagraph('ANEXO 5').setHeading(DocumentApp.ParagraphHeading.HEADING1);appendFeedback_(body);}
  body.appendParagraph('\n\n____________________________                 ____________________________');body.appendParagraph('Directivo/delegado                                             Docente');
}
function appendFeedback_(body){body.appendParagraph('Fortalezas').setHeading(DocumentApp.ParagraphHeading.HEADING2);body.appendParagraph('{{STRENGTHS}}');body.appendParagraph('Aspectos a mejorar').setHeading(DocumentApp.ParagraphHeading.HEADING2);body.appendParagraph('{{IMPROVEMENTS}}');body.appendParagraph('Compromiso del directivo').setHeading(DocumentApp.ParagraphHeading.HEADING2);body.appendParagraph('{{DIRECTIVE_COMMITMENTS}}');body.appendParagraph('Compromiso del docente').setHeading(DocumentApp.ParagraphHeading.HEADING2);body.appendParagraph('{{TEACHER_COMMITMENTS}}');body.appendParagraph('Observaciones').setHeading(DocumentApp.ParagraphHeading.HEADING2);body.appendParagraph('{{FINAL_OBSERVATIONS}}');}

